export function getTripInvoiceTemplate(
  tripNumber: string,
  origin: string,
  destination: string,
  driverName: string,
  vehicleName: string,
  revenue: number,
  expenses: number
) {
  const profit = revenue - expenses;
  return `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #eaeaea; border-radius: 12px; overflow: hidden; background-color: #ffffff;">
      <div style="background-color: #0f172a; padding: 24px; text-align: center;">
        <h1 style="color: #ffffff; margin: 0; font-size: 24px; font-weight: 600;">TransitOps</h1>
        <p style="color: #94a3b8; margin: 4px 0 0 0; font-size: 14px;">Trip Invoice & Summary</p>
      </div>
      <div style="padding: 32px;">
        <h2 style="color: #0f172a; font-size: 20px; margin: 0 0 16px 0;">Trip ${tripNumber} Completed</h2>
        <p style="color: #475569; font-size: 15px; line-height: 1.5; margin: 0 0 24px 0;">
          The trip from <strong>${origin}</strong> to <strong>${destination}</strong> has been successfully completed by driver <strong>${driverName}</strong> using vehicle <strong>${vehicleName}</strong>. Below is the financial summary for this trip.
        </p>
        
        <table style="width: 100%; border-collapse: collapse; margin-bottom: 24px;">
          <tr style="border-bottom: 1px solid #eaeaea;">
            <td style="padding: 12px 0; color: #475569; font-size: 14px;">Total Revenue</td>
            <td style="padding: 12px 0; text-align: right; color: #0f172a; font-size: 14px; font-weight: 600;">₹${revenue.toLocaleString()}</td>
          </tr>
          <tr style="border-bottom: 1px solid #eaeaea;">
            <td style="padding: 12px 0; color: #475569; font-size: 14px;">Operating Expenses (Fuel, Tolls)</td>
            <td style="padding: 12px 0; text-align: right; color: #ef4444; font-size: 14px; font-weight: 600;">-₹${expenses.toLocaleString()}</td>
          </tr>
          <tr>
            <td style="padding: 16px 0 0 0; color: #0f172a; font-size: 16px; font-weight: bold;">Net Profit</td>
            <td style="padding: 16px 0 0 0; text-align: right; color: #10b981; font-size: 18px; font-weight: bold;">₹${profit.toLocaleString()}</td>
          </tr>
        </table>
        
        <p style="color: #94a3b8; font-size: 12px; margin: 0; text-align: center;">
          This is an automated message generated by the TransitOps Platform.
        </p>
      </div>
    </div>
  `;
}

export function getAnalyticsReportTemplate(
  revenue: number,
  expenses: number,
  fleetEfficiency: number,
  tripsCompleted: number
) {
  const profit = revenue - expenses;
  return `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #eaeaea; border-radius: 12px; overflow: hidden; background-color: #ffffff;">
      <div style="background-color: #0f172a; padding: 24px; text-align: center;">
        <h1 style="color: #ffffff; margin: 0; font-size: 24px; font-weight: 600;">TransitOps</h1>
        <p style="color: #94a3b8; margin: 4px 0 0 0; font-size: 14px;">Daily Operations Report</p>
      </div>
      <div style="padding: 32px;">
        <h2 style="color: #0f172a; font-size: 20px; margin: 0 0 16px 0;">Executive Summary</h2>
        <p style="color: #475569; font-size: 15px; line-height: 1.5; margin: 0 0 24px 0;">
          Here is the summary of your fleet operations. A total of <strong>${tripsCompleted} trips</strong> have been recorded with a fleet efficiency of <strong>${fleetEfficiency.toFixed(1)}%</strong>.
        </p>
        
        <div style="display: flex; gap: 16px; margin-bottom: 24px;">
          <div style="flex: 1; background-color: #f8fafc; padding: 16px; border-radius: 8px; text-align: center;">
            <div style="color: #64748b; font-size: 12px; text-transform: uppercase; font-weight: 600; letter-spacing: 0.05em;">Revenue</div>
            <div style="color: #0f172a; font-size: 20px; font-weight: bold; margin-top: 4px;">₹${revenue.toLocaleString()}</div>
          </div>
          <div style="flex: 1; background-color: #f8fafc; padding: 16px; border-radius: 8px; text-align: center;">
            <div style="color: #64748b; font-size: 12px; text-transform: uppercase; font-weight: 600; letter-spacing: 0.05em;">Expenses</div>
            <div style="color: #ef4444; font-size: 20px; font-weight: bold; margin-top: 4px;">₹${expenses.toLocaleString()}</div>
          </div>
        </div>
        
        <div style="background-color: #f0fdf4; border: 1px solid #bbf7d0; padding: 16px; border-radius: 8px; text-align: center; margin-bottom: 24px;">
          <div style="color: #166534; font-size: 14px; font-weight: 600;">Total Profit</div>
          <div style="color: #15803d; font-size: 24px; font-weight: bold; margin-top: 4px;">₹${profit.toLocaleString()}</div>
        </div>
        
        <p style="color: #94a3b8; font-size: 12px; margin: 0; text-align: center;">
          Generated automatically by TransitOps Analytics Engine.
        </p>
      </div>
    </div>
  `;
}
